apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: python-devfile
    app.kubernetes.io/part-of: app-python-devfile
  name: python-devfile
  namespace: stage
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app.kubernetes.io/name: python-devfile
    app.kubernetes.io/part-of: app-python-devfile
status:
  loadBalancer: {}
