resources:
- 100-deployment.yaml
- 200-service.yaml
- 300-route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: quay.io/starnold/python
  newTag: main-301b01145e5aa0777089d6665293dcc3e707d02a
