apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgDEtjQeqtrmtB6GlkME+eiAu4HCRxne+KO8A6lgJ1+0e+IVmkZQftB+QaqJZwMzQrhn4EBzHOlqgljWg+MiLSBrNzQz8CwAddtbtWZ+fEGi9DlpUTnDwTBMx3zGTHXmurvdevNIgjkBlun69ObNQDR66xUwr6AKPDzXc4NWC9FzYLPGXZnHi68E26+YcNtWTfsfhox8/uAD5l2QfLd8lp/xKH6CB+qxA2N0m2BVESfbQFutOmVnG4TBNwDZgPiB8YCcqoXsnJroYJiYHFOf85PDLgIXAwGdgHB+i0YBleW8QpWxRWQY4hPiR+J+y53FjVNmp4ycrbfWAlJdWtcg1YiuA5VV38rw0LwKw6edj6QPWWq6fSLixjoQ7HgLOUxZ2Ho5b8Uz0Yoamruc5LvhJhFVQrQRDZkZdjFAeDks+rea7wtB3DVpAUoPbqMcFvmWtMQA+l0eXTItkI4Mbiyg21rnWwRwBia5SCgpAVs5YwTjUFbxkyobqOZSaxSThUUcCmS2iK6gfeFPW1o1iJ4hKz47Oy1DbGjJ+Oatt445DOOWmgmoFB/bbaQs1WL8oYUmRUsm5jFLv8cSTk9+wE8o/R3FwoN3Cx3FjprHXbNWQkAsc21uwu/TBq7jVKUpLmI0kQzgExbQGK70nODOvh9hDHg2jd2VvSOwJGeJjG87Rt2WbAKOoAmOri8f7mMUzhYqnFSFvncWSh/7Jp7RIWhK+bqSCbT6lDG4hJc3Gfl0xD/VMV9g2un3ceIXeVOe0p2qScPXiBWEtQpnCXhLzsnJeD+JWfkij5I1XMOsMhsNrZB8wg6Hqwh/tLPikL72eAoZ6nYalkl0wJokF4HZZC1iV9mJA9JZFZxjBaENhPwfqPe/v+A0hkx1ogEr5FqEOzMXUhrIFANL6FvvXPA3295ub4qO8Kru9XmCvTLSM2+VFsVv+dyY7olW7oJbFGg4dxlWkk3rulSz4aZE
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson

