apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgAhWjSsb0KCjpqy9ShNYvZggjeXf8t8Uy+LWOsqYrwwJgrpamx2afbcWN7q41S8bSvaN7MJpouLJcbck4ocayUA2w/BZ1Bf8MUnbHm+tkkyiZD2jJIUYKGPxw2vlVxYj5R9dUJFEvhlpvA3bziRt3LNKKteGvwh6hqAV/B7BqpF6SEoQUPk65V9pe0N8Nfa62a1ybLHan5c2e6w3Fq/3lp4pNhytNmTmGEV5hoJiVNGrpjlEOG9/0B9b2FkLWJDpiOuRX/ixC/Ce3C3mGE65pXr8k/X3z7ZESbASlYJoTfiaZmP664a8z+y61nXqQIA8rBWgATKNt4El0kEpVtQf1HVGXozamex4jvN0T1xKHtsLC2D0AfFJ7dJoDlS+7Q1uLq6YuiRhEQaPWTjraqrUSF+a7wQXXhQGqT0NUEFxSx5x0+owjnwJAqoVL/cgN+BCrHusBJGLCuJT1rxmpQ/hIBH9wCXrHkH0M7EaI86oJooAchvYGUOr9Dhs6Hcgh1f60gbE4LKUxN8w3QMsqZSaDOKcKul4Q4fwxDI8BiqJNrD2QnEChvTrN1jtj2MPXVT4zzN6AeZAgQompfz02dA6TOSxbEFk8ufQjGRNvglNhDkmLbaQdL3IGnZHJJZX9J0QfnJiF443IyAcdcUgUMKpjrFTT54K140fGE8WvrE79I0aaEqfqwCJqULT9WgKIleunaekoie0Q65i6xAEV5S4ttPwScge8SUdPSyDVOabb9UmBtDEBxSXtOp5u+Mbp4blVIA0aJ/6pAqDq2xVu+lG2JlSk7HFf2Y/OiOjTIf3lB+uzVxOv6Rtx4wDxVbXVW9+fwDQIb+2dffTj5q5rH3NsMGl3y9Wk56+XKcuWtUitn2GPhr6IsNCa4aENmUdMHTfeZxHEVNKFiDc0OMJU/h3MUI1kj5mEPgfChz06HOU5/gL8Az+FcqiyBC7Q+2Ylum16HqWhkK0PJa
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson

