apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd 
spec:
  encryptedData:
    .dockerconfigjson: AgAqcErDjZ3kCGqmPas0v0zYc1/Lf5zpLGvvLdh7WHyheT270UVlAB2B7QCSe9kfu9qfGRg18h1zsoFsjLAXVI6u+EBrRkPbNfbDuKjd1fIKveQBI1+3z+YS3dIw1navIgoFgHp5V7e5NrPpzUPSD+j87ZY2/KKFA+QVP9eTm9zCg6emkZqvaF3R65fEnpiYZFr9H/mghyY/N/xjURvhCWxFBl9b36mMy+XOscaPNhM4+4Ttu6ZKWXWqQbW17gk5YJUhtiJdcxbSmEDQ1xOC8k1V6UOGz+SSGhK9K1JaD07f6nEXR6wBTuurk90f2SR1Yrot+dxoUvXJgI5ZH14OdDO/El3FQYUFMZMaQpJanNK5tkdvj5cVp7VqdqxCstpObzUR2Po9gyXz1TP7xWh6cp40TV+bfupNSnMuJ8C6h/8+hU1FFJDI8oqLsFW0KNO0ZqAQF0dpW04r2+qOC7YWqKbEX71rSBEf7nCpgpdEWMejcGtMgNpUS2UW2jRbh6+fqcl29bp8/Iff4mAdqdyUBP9G1rKdn11vIlrnL4yphgfBlhJmr5tuYZKBZM04QrHZRtYpJNzS7oVFAyH5EAQNcUOMsJGcJUVoAPsQV8vl9XsJBhl9+MOexEdaLWEvwAiVMBrl5uIJwcpvIrBwZWz2lu1fhswGwwXSPUAmIRS7E4dUP1OkgULzew/qVVc9NgDCbt4JB/ffFoYDKuUQN0DXtcYsOJT47zTn0NX//VtPslympvDX0xk2zKFxtTme85ciAH4GBRYiyh+kDzpXN9/DiWRrf+wXmFdB7//zPwlOEs+u0tKRJmz53IA5tQbaBhZcDMyCg1KmTJdoxNwNSOuSFNBRWVjOV81pn2qvSjsxedGbT55WEZ0dm2fGKGqURKlHxb6APA1IwpLlKTIPNaNlUBdQIKTYfP7Gj9cWD3sFakk72bI62f4KV7TusxhBLeaTLRg/VVnj+Dmg
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd 
    type: kubernetes.io/dockerconfigjson

