apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-access-token
  namespace: cicd
spec:
  encryptedData:
    token: AgBrhXq7EuvwShZ+jZRrv974EKEjtHmggVZ0ZFI0hCOw9tW7PTgObmNmAy5Rj5tlAT8cRPlwlHlZeyagHDJUaFGtpNLjidgKI9Yv0A8ctPJ4kkbMXhcGCaSX2I8LTU0fM8QQ0XJOPqDpdxY31CZpn95uzkk95U6JmbjBIKAgU08JJra4xTtAEfFS+aMOwsWnmlArr8VTEcf/p7qwYgOGVsxmH3mogJbZfA7sAkBASAIQ0ZNiDpLaPE7X8p3s9zHmsB/+lRB2tf8Pv7p9YFWgKYJi0oxQHIKTvxxeZYRolc/FKb/m5Dn86Abyv409GvvVFV03lMAytTB+mYhcamrE2xRM9lPwYY6gnFjXGvLCiazdHNkMiZSG1VRDA5NSisBVV4OcB+7ObYfgnxm6zp+DKaRCAphMsAnd+0BFZlPV3WWXNSyyyRFJnYKvq+wjIKN/5KRt3X5KSEjM/Ypt4EKnSS2lgdHSg37STZwPL8lMlRcaY8H18PfV7/yu2QTaREx4tABSYU491p2Lxz8D8aB4qGNUHpLCOARyu4Qks/EdWjxbN+egSKk7HsYfYHu/QvgcAPaofbXSi/i+UD9TgejG12pXrsXAAveJjy7vJKg7hf2SEh6q6/Dx94PWRAV7LHu7M0zMp68B5ptRwmb1rx47tClR8UsdnnATOx6CqnzH18oLJ0z3ZS741IWhTGsqNtw9uu0Mzmmzm4yG5Le5Le9lv6E5rwu4FINLQnpnhuuptrCOeDjQU0S3cNTF
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: git-host-access-token
      namespace: cicd

