apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-access-token
  namespace: cicd
spec:
  encryptedData:
    token: AgDA7By6sG6vg7qG0fJvMBgz1Nz7MlsA/IMk/jstRtbjxY7KX+/OdHJN4OAynO4jAUi2fJ9Km4/zzJ4t/DWqCDbodivZAH1rE+BwjogEfpey35Goo1SJaIelLlCawuck2ZOuYSFDY7+PoIQtOsfjwyfnhKSqLa64TufO8bFj9kkL6u3MzDfa3ZWUHguBdHRUjltBIky69na+99/AXh5rA3XLKYSPkIz8lTz9ucjrb2Y228SrRBydpCZSX9q/uON8Uhs2wmcDPoW1On2+iPvqujdiBoEwYnMJ+WiTsO3FNgJSmRfG0cj+drPx3kWe0B3UrLGDvm+KNIYKBR3zWt93bl5uEEF2KgZhQ/sjPHLnIpRnsMR8ryd5rmmE7nXy/xJ9jkvuxnebvJ0Dg3fKpaCRbNv+8eMrorRA6BNQUBCShD+sXJbExO0exdMPkzeOdGDz1sqtbasypKSEOY7qGixFLDvbJFpL6UL5qLrASeXcSiLGd6cQiR+9lqP0ajL9Jq7YiZkVRLLVgAQ1BQNy1CrQrlM2ljaFuCh4ZoJ+1no5iccSL4BPPSm6vPHqYwbJmJhd2wGUs64o0hDR9ffnvlsuRpD4b9UZlqSH7oGAESwRXNSFC0esbZX6t+1cE7xob8Ddqj0/cnY8Ky046vfDYmQyt/zqhJJr9GAE+yxwyGLALwM8Tc+rI3L00TbB/z33GBeix8unSCN8G7vl4QkeYqR0ffniZwSv0rVoVu02K0yo+pRFqww2C8tWSyBE
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: git-host-access-token
      namespace: cicd

