apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-access-token
  namespace: cicd
spec:
  encryptedData:
    token: AgDIU+NbMtpboooNZMr0qUl+hECzIdVg1liIUB55lBEIP8I6xCOFuUJO1fGFJB7DlqPDxUVrtCCyWHAH5vmsvzEf4QCN+tiE8XgwFgwoT4gn0H9Ep+gdvsbq/MCuo9ZzTV6zmGtsY7Yd703Qvjd+GUT5/6Peq0DkvaOFVYbKleuGdeDGeqpokp0NGPFnQJi5dL+EcpN7hZyGXByV6IXw13VOWOt3WbyTvlbtmXa7aw/hPPXLd1Of/pQNuHGMRWvpeJtJjkzP5Cls9/Rwc4tDfmgoSa93NDtYmNdlAzW2nu7d1T5ZWq3mEUXu7UoPlHLRUeP94EnajssBvhBYZxVx4y1kQCkFI0qmPzeY04SikMMnLv4uXC7YwTepasgeGj9LS0UGPjfBEfxgpRcuAdUPkae9WQTI/dXgd08yoOvidaWHDK04TU46S42KUtLUQeba/1Xc+AeLlMl5MqalqRiscDerEbuX2yLowZs+gk8fb5kK9M68vFrs6gMMWe9UlEm6gMttt9CvZTkLIKzu5G4+uwvjOji3lN/sE61NiO4aByLS83O41ODu3jU45OYyO+NlWEum0ME2rlLecHMsItCmMGddjWqDkQU1hr6Fl2ewXR6SGeqO6qKBlqsbfNGHnX6g+F9l8+J3lM+OAS/FmBxc+3Te4DXVjMrXHn2tELnkkLv8Y6Gh9JSiv0FycUxVFFfNElQOATFYsHf6mSXrKd9DEkFT3Iyqsq772EMfkmju/qAoxhdUxVMeYgCE
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: git-host-access-token
      namespace: cicd

