apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-access-token
  namespace: cicd
spec:
  encryptedData:
    token: AgAaun0bdQIA1lj+kRLJDfneUj+bYTtzlcv8pCmPLEVb+Bem/S0+N0nu2nhoUBfU6/TNpfM8GdrXYWVL11KK8XQnPyODZQTaf65QUh4fLHUpK6AC8QyZ8ZAjQ7f6jA5H3L9zCFQ3RkYeRDzPGpU60hAJnuW5ORi9+8Wl8ENkxzP9Ju44lp/IBsCIJauwhVGzmqNYvFYB7fK3hKwdzvIzahTs1iYYRQekMre3CuwaUcsCOpQXhl7DtZlgCD4yFZJyzrEdfNWvwFGy8+A+DHHdlkyqmhkAeMS5l/P45RSBDzSDvYbDJaFeCqoGMML9kHhRXMzt04M/tH7HmhLpLSFT4bfCC00Vu6xOOpJOQ7Fhlk6Zif/uQW5is9vkoTAIhX5tKWb81y9W6PFQsLwBKtULfH2ZHy8gK3F/b7PsKRO6UlTt+S0bys5A/u8GeGxz3nx2USWDeCGwP7EYcnmdH9jX3rv+pgUmKhGwlRezLqHz4CjH7wcfb/F5SslgnT8dhgcGC+hc5xY97IAVVdg8Bdc1HCtu2dkK2q+wzS3skUq0BAGzq6pAHJe2/sPp05eCyAV4jzYib5vzCHRxTuYwHLYBqtBUjLrpTVVtmLxJtBhswT3MCF/cvATK2P8y1K9kSoCxJ62XnlJ7sRb6nWvtIiKEg4T9epgsZsIV8eXjzdHVirPXQnESDPs7fxNMgZPTnmDd+g4AgoGBltX3jocyYNRXsuAENcm+ulBb8vdGNneWbIsLLklGBWIayIcz
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: git-host-access-token
      namespace: cicd

