apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: default
spec:
  encryptedData:
    WebHookSecretKey: AgCqJEArYfNrEdlkNYuFSL8xfb+zGedeEnkKfbGpuU1mhwA+0Tos49hwk8itLqFgeYKYjAGYadpsLt+S7VBJkCeTVQ8+gqRAC+DAhzAhT90we3pyXy0c+jNhUzd6oiVlVUVzyXW7Q24Is0MRvE98oi85PDHVtKCU5nOckZhGbCMXPyx4niA53krBABkGJVno3RBEX3FpQdGD+Q+s78fc559za/TdvAPUKN/EQ8DJzI0j4R34BbGwAo+6/HltHmiTQwDzHQYmzuDMMJrdz0Tu34k035JZnHYNGvarmbWWpqDP4E6mGWbv3RCo40xuc8GyJXFrfVMlZiBo5FOvsj2C9O4BcqHe/8prLMQ4JJ4w0mgkh9FKoSoLBfqqRRSb6Cq5z689Xd1vT8/yiVDvUg1vjsQOSrXZc2yFGaDWvF8lmGi1qWu5jFGyJimSokL/w3geutVVTwgALa4KIrvNs6I2CgumJ87kcyQAXgqdCXtPUngnGBJDdTmF0FrZ49DTf8j2EXiD/jFIJefvcNJsMdWEg9yvVRjgg4rtZ6OZapwEtGiSM+gQyIvdr64Hh0AEXPc5Gw8Ld9Rn3+fGHoL9uV5OahMHadgVy62j2lSbZJXQT5YZ4TEZ07+OoVwtwbStwBX2faVnDRur0yJu0S2bFuYtCf65IPpnDtgKs+1vI6FUJ6lFvxIDZr0XcPTAABdfQzhGZ7oCOhgmXmeG9U9TN2JUw5g=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: default

