apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    WebHookSecretKey: AgAdZsTOSzd+su0adSBuffeU/XR3cT/0YrG3JvKI2oKIbq1navsV57Zpa+BQ5HrzcVv2nmB+27ZJsJON6emFvRx7b3G3VQZro1aino+nnu9KBj2Hy5NfB5D+fZPvAHzpLXLry8K8dHtoIxGvDLJ0wGZUj4S5SoTud8WA76a5DsPK74CvGfuWKRcYqA20P1VHAsHeRFUt1/XrTVuE1wU/Q9EYK1XJkgFYhAwZwroDDAV71uhcq9vt7lOYcRgcLGRfjcI2mqJIvdTUdqWAGbkjECNvYAbcwyVbEaXRb88lTfy6wGeyjvVahI3kkm48FnJNYcd7TrUEb47sXBKQ+LWswTQRSD9Q+pc95F7Gnp5z661Cby5avDM19onjdziU4k3vz3ZBLPhDyusEbVicJHV13ED/Jxd+okVpjFmLpYhxm0j0ICk0F+4uTQjohOEA4H5OF1ikizNBJbGNWIQ+287fQlafquh94U8EJRvqqaVg7iIOPTRvMH7Fr6WyAqGZu/KkvDMMxCPnOIIiDXvcxUEp3ig5Lo96dXwO74byq7wVeMbe8VbrTCGW1lUd2+qkcZ0zVikiZk3WCo9+gUVMHjw0zgznrWyD6ieOPigyL8Mlavv0Vd0uq9ar1y0msXfcutOLYJkos94HQx9NfKXD+E4zBdwfUycqQkq91xW5lQoXAEInnTcAkzuSEkC8Cu1/E7vMHO91q3kzGrIiC5XHvikGb+U=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd

