apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBYtWD/uG72l1YSV6QD+Q3LBjwLwzv7USog/vfNovQx+Vkc2wjwgiSdWeYZivID95vYguuwOqUp4NMV8uNXnHspkU+o6oLQJHEAZFDCsZEE2My3jDfGn+SfpBsnn1G3HlnXWN0Lxc7hRR7y7WcChZ8N23vb7xoUEUdYT7byWyReXf8kgp0gw3pKYdkYBvbjEoBOZwPLizUgItjEuY/FXuEr/ce4PVjRGxYo4r1DPFGQwekWU1sJTw2JPvsd+Kt3Lu5eFiIbDyVnNpwjMWoxNxyzTS3RFP8/UNIUiBONX61RZ4zMB/PQy8Ctv6ohAzAxxv+FPh7D9cfGiSUFKna9QI9ir1iCA+FlWaDmY0YEpm68bdxMWpFPU1ErB98rF99UdFIojIaIyLgHMYedQZ09tw7WCg0v9qFM2Ro0d8lhIVrxQa1sZO0FtVA9X8UEWwYOL/l66/pnQX/vD01lnken+YZcxuFQ0yu3vnfy1WO8gVWLK/6xNhx5tt4d5QyqOh92t2w34oHFJo3b+7c4unfy5SEjbZfWJyEXIaA1/GClaA0Zz066vLaRZmi9EWjs4m5bI5jE5c7GguWD1GIPEVwsCVea7f6NHrlFLTDaWn4x498quoobUC/0eRWIRTXaRJNbAOhXTX8XS8YC1HLBM3B+6Ng5y/T/TDvEtltoG9ooFwdg4tVCfzCGhZmBAsaddhZ2haoZYmjf3h/QcOmFQUs1oQJnD0L6Ww==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
