apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    token: AgAPxmhaDaw79itE9LAujuJYBJzZ1qda01xaJ5XUsNKFP85M2mXEktS1d9HYLcqAJgmgbxJsc/4fyeau7YY7F1fAmc/8DKCFb7/GmiEGHxYs8sJXguQ70gRQOr3PawEoCbVyHoq/VLkdFFMXGMSSCWQLvtkRUxU0apN2blMRC8t8CfvPK+33Weya88L8VAZTXirR79O3k2LRQIU4vhCIUJ7c3lBRvA9JLy5k3hoIIQh+n/xlSeOIcdxDYswxrv+wbPEWTZ0xB8wCawATtI816Z+bTI1Y88xDdZNoTdmNuY33kog/H3Vtwkcfi0heZ22NKRzdP3dJbAIPrKnNM1Z3iX7/jVoSVqhH7faXsUgf4V48pSyRf+Pemcw+jTjdQzDwagzWCDUzlBjrp1Nnl+J44LzUKILd4qBKF/LKqu2TJxuPq2ocDS4Q1F1waojSiDJexA3188r6f5L+Z+0uDPrTJ44wkH9R0xP4JcpVvyRsBEsBL+2TyxtzA3zGmolT2OQxyI4QnRsSpqUb1sDnkX4rVkC8doUyCBc5HGjEB5Esl7En9MBJLV0wjaP/66cx41PdsgELU8ScUZllB78AFclMkOzBGqE0bfq8ojlZe9vEJxQ5BU4NI6+2MhopvK6Hw7WBAntgp/tLsC85GWZfiS2VDvJqNZvr2Xfe09nyMtnK9/DKyz1yAFSyINcFWc0DCzg29Sid9mt0+ErVOclS7yjiAvQ=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd

