apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    WebHookSecretKey: AgCinFTKsv5pJe8WoteeHn3YdHsiHLhrkCaqylyptbKW0dC3+l9GOhyp1nGu2diOOPdnUwW7PBlRZo7k79uvvlvJEvmjwQ94gucTZptNBGDcKozfTRluk095iFi4vYEYIF+TGtaX+n6B7cdOFkDJVhndsE4wpoCz26LuLSqWV3Khguar4I3LH2PM3XzupBwH6sm9e+6KCsvHP32vyF+X5tptj0qyChx8zirOF5/+poxWxzUj1qOeT5eQ7HZz7yWsHt5LUfXOdQ2DMqcWdUA8CRktKmDahceMYgSZVzT0TIbknnuKY//eJB4UN1WuwcC2SgBLzWLMW9XZ8oIY1JdDceYiN555heNGyhrT5f0Mp8q3FqKUXUQGXUnAXtI1oNqgiYUIDdrioRAOv/QEM6Vh5MD0Q9kCvq98EX1vNelbA9Xgng2f6HbCxru4fDz/tSlGlt/bvVqCmTgpcUucsmZn9KEAzXrf6veHvkf/16AV+LetJMVlP3Z193o6pkeNu1tiTlSR+Ev94aEDObqp3hAcKtOod4rC1bvYVuiuju4wUPUEBUzCpKrH/dOL2X7YehzCijd7wN53UKwMBsWpVL6P7uy+h4OIhnUoQOCjeMWhCTGFc/iwSNZ0Jkl2R0H7DYwKQVlVthAyuinidVwXcyW2JOJQhfM4z2jvrkU/36JztDKklkJt+cLkZ58UeA4bW1af/FxNh2BNs28RxXyECE+2PM4=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd

