apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    WebHookSecretKey: AgCaegFjGjhIA0Mnl2b4WMKAhKjIcePqFh44PWHODZoQOdXX6ubBqIVTGIy25WUJ9wvkSfiXsa0l/dpahHSZr82MeUNo0RcK23eLhr3by/zQIKguaktsCQlltfT5M9TM1YMJOFYU9U1XyT/Y+SefPN3NGt343ZvT3zNxG7CWTGZkvJ3Y7uQ4+vQIYFHI9Kb/DYVL4KClc0bOe9QL1Rm64IYKN7g329M9ltb6UNL4PTJ93ufDimVihGNsStb1b5qTMag54K1YaK+61u7jxSWvrFapwm7PyPrdHMbjpXgdx+kQLlZdwORXqLdzbduKBRiZCiPRVc4cApzILOHUy7CAnpD/TTIU9+1onPR5xBPK8C75CM+fVZF+K/+7LXJ7H1w64plTAJFJvCK4tMxpVJ8T3XwhM6zotGSHPqAzJqriHCqWo358/i5JFyVp7GlWKB8Es/XjRe9HIP4nBhBUjq+KPT9AJGKQ3D9ereDd50qkuYQoAzv/CT7nwEIfPyDWvEX9f80n/89YcvEn1RYrRDx9u/835u/qqYr/2EYhbYVGAcU1/BUwiA5bT0j1A4J2eQ4XannyflEwGV5QX4B57fHeG92ZQtVDvyuxdiWSxDxW6etkQHOMe/BckrUHQn+Fqp4JB7Ao/qpfKXY3GunYcBIpcMCVeDUQcDvRyj1YMKpEDxXvOOXwEYElOoELWm6g1bSQ5Aaof6XsUiEV5KZS8bnGzVo=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd

