apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-python-devfile
  namespace: cicd
spec:
  encryptedData:
    token: AgB1k/F0TE8MTnm8R6glGPAkvYnYGf9qtAFu6zGaNtzeImuLEiyBLjZl6ntaXFfTZCc5Sh1/HT4rN8juf8JDR7QnfPKLetU54u5bI+dqC3D2vjsy+ZkO6mmMGjhZ41TPCMh7m0uuMUa6MjxSxNGAqpOykaUPWDBLXlvnHadInqfYIzxY+RXirdAjPQpGFUsPCx9LfFHCnEaqy9G+JIePL6j6jfVliliJW3n0I4Hj0sWwlvXuES+w8FVi73Zua45SO+y2tP7MQ+SBO/7ebNZ/54Qvn0StBJm0uI1HWDsirAGJ8h5SQN1qyv3lS6Sudwig+XJITs5bdcMYA8R0xE/Al8+0XMiunVeV6fVzsu8XneR/PDfJnMpKa73ivJ1UWjjRgtnMMWCCuFCEnIMYe8SOU2nqJ6cH6cuJBzeHEh6Fcu6Ju+6RcMpCpCWmhVYvyU9qRYC13j4PxFoybaPVd0qQmdq0SAq0tpNFmfRctopovUQbsdiX3/7YiG3YvQjk1cV9AvKpHjW6MmUNw+UM50m9pVCzzNILzDB4NkVaslV7aB6Sr55RY4JzAt6XXaALCGzO9MbCNXd5Sbl+mEtchypswJg/tP/h0VRzkYVCcf278iryOM/GTuCiypZZMdvwaP6RaRi8GZ0tCUFztzT89iN7yQ3voxuyCHWBUV/XBTmkqvCD64G8rJrMCQDZrLyZcsZPqsl9jO9x2nVUC200dHP69FQ=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-python-devfile
      namespace: cicd

