apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  creationTimestamp: null
  name: app-ci-pipeline
  namespace: cicd
spec:
  finally:
  - name: set-final-status
    params:
    - name: REPO
      value: $(params.REPO)
    - name: GIT_REPO
      value: $(params.GIT_REPO)
    - name: COMMIT_SHA
      value: $(params.COMMIT_SHA)
    - name: DESCRIPTION
      value: The build is complete
    - name: STATE
      value: $(tasks.build-image.status)
    taskRef:
      kind: Task
      name: set-commit-status
  params:
  - name: REPO
    type: string
  - name: COMMIT_SHA
    type: string
  - name: TLSVERIFY
    type: string
  - name: BUILD_EXTRA_ARGS
    type: string
  - name: IMAGE
    type: string
  - name: GIT_REF
    type: string
  - name: COMMIT_DATE
    type: string
  - name: COMMIT_AUTHOR
    type: string
  - name: COMMIT_MESSAGE
    type: string
  - name: GIT_REPO
    type: string
  tasks:
  - name: set-pending-status
    params:
    - name: REPO
      value: $(params.REPO)
    - name: GIT_REPO
      value: $(params.GIT_REPO)
    - name: COMMIT_SHA
      value: $(params.COMMIT_SHA)
    - name: DESCRIPTION
      value: The build has started
    - name: STATE
      value: pending
    taskRef:
      kind: Task
      name: set-commit-status
  - name: clone-source
    params:
    - name: url
      value: $(params.GIT_REPO)
    - name: revision
      value: $(params.GIT_REF)
    runAfter:
    - set-pending-status
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
  - name: build-image
    params:
    - name: TLSVERIFY
      value: $(params.TLSVERIFY)
    - name: IMAGE
      value: $(params.IMAGE)
    - name: PATH_CONTEXT
      value: .
    - name: VERSION
      value: 3.8-ubi8
    runAfter:
    - clone-source
    taskRef:
      kind: ClusterTask
      name: s2i-python 
    workspaces:
    - name: source
      workspace: shared-data
  workspaces:
  - description: This workspace will receive the cloned git repo.
    name: shared-data
