apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: app-python-devfile
  name: stage-app-python-devfile
  namespace: openshift-gitops
spec:
  destination:
    namespace: stage
    server: https://kubernetes.default.svc
  project: default
  source:
    path: environments/stage/apps/app-python-devfile/overlays
    repoURL: https://github.com/starnold-redhat/python-gitops.git
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
