apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: python-devfile
    app.kubernetes.io/part-of: app-python-devfile
  name: python-devfile
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: python-devfile
      app.kubernetes.io/part-of: app-python-devfile
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: python-devfile
        app.kubernetes.io/part-of: app-python-devfile
    spec:
      containers:
      - image: nginxinc/nginx-unprivileged:latest
        imagePullPolicy: Always
        name: python-devfile
        ports:
        - containerPort: 8080
        resources: {}
      serviceAccountName: default
status: {}
