apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  name: python-devfile
  namespace: dev
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: python-devfile
    weight: 100
  wildcardPolicy: None
