resources:
- 100-deployment.yaml
- 200-service.yaml
- 300-route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: quay.io/starnold/python
  newTag: main-c5f23b77f83e5fbb34cef12101d22f5989da1c4b
