apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: null
  name: override-image-tag-in-ops-repo
  namespace: cicd
spec:
  params:
  - name: OPS_GIT_REPO
    type: string
  - name: DESCRIPTION
    type: string
  - name: IMAGE
    type: string
  - name: BUILDER_IMAGE
    default: quay.io/starnold/pipeline-kustomize:2 
    description: The location of the buildah builder image.
    type: string
  
  steps:
  - image: $(params.BUILDER_IMAGE)
    name: update-ops-repo-with-imagetag
    env:
      - name: GITHOSTACCESSTOKEN
        valueFrom:
          secretKeyRef:
            key: "TOKEN"
            name: "gitcreds"
    resources: {}
    script: >
      #!/bin/sh

      cd /workspace/source

      git config --global user.email "starnold@redhat.com"
  
      git config --global user.name "starnold-redhat"

      pwd

      ls -al

      ls -al gitops

      # set image for dev deployment

      cd /workspace/source/gitops/python-gitops/environments/dev/apps/app-python-devfile/services/python-devfile/base/config
      
      kustomize edit set image $(params.IMAGE) 

      # set image for stage deployment 
      
      cd /workspace/source/gitops/python-gitops/environments/stage/apps/app-python-devfile/services/python-devfile/base/config
      
      kustomize edit set image $(params.IMAGE)

      # Push back to git

      git add . 
      
      git commit -m "$(params.DESCRIPTION)"
      
      git push "https://$(env.GITHOSTACCESSTOKEN)@github.com/starnold-redhat/python-gitops.git"
  workspaces:
    - name: source
       