apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: null
  name: override-image-tag-in-ops-repo
  namespace: cicd
spec:
  params:
  - name: OPS_GIT_REPO
    type: string
  - name: DESCRIPTION
    type: string
  - name: IMAGE
    type: string
  - name: BUILDER_IMAGE
    default: >-
         registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:afc5d3f9efe26c7042635d43b8ffd09d67936e3d0b6b901dc08a33e20313d361

    description: The location of the buildah builder image.
    type: string
  
  steps:
  - image: $(params.BUILDER_IMAGE)
    name: update-ops-repo-with-imagetag
    resources: {}
    script: >
      #!/bin/sh

      git clone $(params.OPS_GIT_REPO)

      curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash

      # set image for dev deployment

      cd python-gitops/environments/dev/apps/app-python-devfile/services/base/config
      
      ./kustomize edit set image $(params.IMAGE) 

      # set image for stage deployment 

      cd - 
      
      cd python-gitops/environments/stage/apps/app-python-devfile/services/base/config
      
      ./kustomize edit set image $(params.IMAGE)

      # Push back to git

      git add . 
      
      git commit -m "$(params.DESCRIPTION)"
      
      git push -u origin main
       